### ISSUE TITLE
Make output less noisy

### ISSUE THREAD

**Issue by back2dos** [back2dos/travix#1]
Because stuff installed when the test itself is run, the output is much noisier than it should be.

Running commands through `haxe.io.Process` often tends to hang. This may be an `--interp` problem. Maybe running on neko or node could fix that.

**Comment by fponticelli** [comment]
Also it would be really cool to have tests that are distinct per target. That way you could decide to `allow_failures` per target and it would be easier to spot errors that are generated only on a specific target.

**Comment by kevinresol** [comment]
@fponticelli Do you have any idea how to spawn individual travis instances for each target?

**Comment by kevinresol** [comment]
Just discovered ([from the haxe repo](https://github.com/HaxeFoundation/haxe/commit/116f734d7c2b5bc6aee80ad4da700d219dae67af)) that we can fold the output with `Sys.println('travis_fold:start:test-${test}');`

**Comment by back2dos** [comment]
@kevinresol I was happy to see the commit that closed this. But I've just had the opportunity to see this in action. It's been quite a while since I saw such a trivial change have such a delightful effect ... thanks again!!! :)
