### ISSUE TITLE
Distinct tests per target

### ISSUE THREAD

**Issue by back2dos** [back2dos/travix#10]
To pick up what @fponticelli [said in another issue](https://github.com/back2dos/travix/issues/1#issuecomment-217263913):

> Also it would be really cool to have tests that are distinct per target. That way you could decide to `allow_failures` per target and it would be easier to spot errors that are generated only on a specific target.

I'm not sure where this is going. Somehow I think that (at least most of the time) it might be better to make the distinction in the tests and not the configuration. But that's a bit abstract. Could someone bring forward a couple of concrete use cases to discuss?

**Comment by fponticelli** [comment]
My case is mainly thx.core. It aims to be multi-target and incredibly (?) the most inconsistencies come from Java/C#, sometimes CPP and less frequently Python3. The same code is supposed to run consistently but it doesn't, the generators are simply too different to provide consistent results. So it has always been good for me to build against JS, commit my changes and see what platforms I should take care of.

**Comment by back2dos** [comment]
Ok, so to be clear: you want the tests to run on all targets and allow them to fail on some of them, without having Travis consider the build as broken, right?

I'm not sure that's such a good idea, but sure, why not. Would adding `--allow-failure` to the builds that should be allowed to fail do the trick, e.g. `haxelib run travix cpp --allow-failure`?

**Comment by fponticelli** [comment]
It is not much about `allowing failures` (which is very tempting for the Java target) but more to know what platforms failed without having to dig into the script outputs.

**Comment by back2dos** [comment]
Ok, I see. So you want some kind of report, that summarizes the result of the build, right? I'll see what I can do ;)

**Comment by fponticelli** [comment]
That would be amazing!

**Comment by kevinresol** [comment]
I also think that a env matrix should fix this

**Comment by kevinresol** [comment]
I still think that an env matrix suffices.
