### ISSUE TITLE
cannot install flash player on linux

### ISSUE THREAD

**Issue by nadako** [back2dos/travix#108]
looks like Adobe broke it again:

```
https://fpdownload.macromedia.com/pub/flashplayer/updaters/30/flash_player_sa_linux_debug.x86_64.tar.gz:
2019-02-12 23:12:40 ERROR 404: Not Found.
```

**Comment by back2dos** [comment]
Suggestions? I wouldn't mind just dumping the tarball into a github repo / gist and getting it from there.

**Comment by nadako** [comment]
hmm, it's weird, because the version `32` is downloadable and it's the one specified in the update xml file, so maybe it was a temporary issue, i'll re-run travis to check it again

**Comment by nadako** [comment]
huh, i wonder if it's some caching issue. for me, `http://fpdownload2.macromedia.com/get/flashplayer/update/current/xml/version_en_mac_pep.xml` returns `<update version="32,0,0,142">`, but travis somehow still tries to download `30`: https://travis-ci.org/nadako/hxjsonast/jobs/492800879#L2857

maybe we should add `?=<timestamp>` or something to the url to prevent that?

**Comment by kevinresol** [comment]
wth, isn't travis an isolated container?

**Comment by kevinresol** [comment]
seems working again? `https://travis-ci.org/back2dos/travix/jobs/502596967#L346-L347`

**Comment by kevinresol** [comment]
Let's close this and wait for the next Adobe surprise.
