### ISSUE TITLE
lua testing doesn't work on haxe 4 because of lua-utf8

### ISSUE THREAD

**Issue by nadako** [back2dos/travix#109]
```
lua: bin/lua/tests.lua:55: module 'lua-utf8' not found:
```

**Comment by kevinresol** [comment]
iirc there now a haxe-dep (or named sth similar) on luarock, which can replace all these lines https://github.com/back2dos/travix/blob/7211083/src/travix/commands/LuaCommand.hx#L56-L60

**Comment by nadako** [comment]
that's pretty cool! tho it seems that haxe-deps actually also depends on `luautf8 == 0.1.1-1`...

**Comment by nadako** [comment]
Actually it doesn't seem to run luarocks even? https://travis-ci.org/nadako/hxjsonast/jobs/492772845#L704

**Comment by jdonaldson** [comment]
Here's that haxe-deps package : https://luarocks.org/modules/jdonaldson/haxe-deps

**Comment by jdonaldson** [comment]
> Actually it doesn't seem to run luarocks even? https://travis-ci.org/nadako/hxjsonast/jobs/492772845#L704

Could it be failing both the `Travix.isLinux` and `Travix.isMac` checks?

**Comment by kevinresol** [comment]
Should be fixed now. But requires ubuntu xenial for now (`dist: xenial` in `.travis.yml`).
Because luarocks wants CMake3 but trusty doesn't provide that.

**Comment by andyli** [comment]
There is a `cmake3` in trusty: https://packages.ubuntu.com/trusty/cmake3.
