### ISSUE TITLE
support new targets: lua, hl

### ISSUE THREAD

**Issue by fponticelli** [back2dos/travix#11]
This might be a little too early but at least you have a remainder ;)

**Comment by back2dos** [comment]
Any takers for this? I guess we could just `haxe -version` and skip the whole command (maybe print a warning) before 3.3.0?

**Comment by ciscoheat** [comment]
I'm working on getting lua to play nice with buddy right now, so I can add lua to travix as well. Good idea about the version warning. Do we have to use `haxe -version`, isn't `#if (haxe_ver >= 3.3)` enough?

**Comment by back2dos** [comment]
@ciscoheat That depends. If travix is run in interpreted mode, then that would work. If it is compiled (maybe it just shouldn't be) to neko with a specific version, we wouldn't know.

**Comment by ciscoheat** [comment]
Ok thanks, I'll use the version check then.

**Comment by ciscoheat** [comment]
Getting closer on lua with #22

**Comment by ciscoheat** [comment]
Now when Lua is working, moving on towards hashlink... Nicolas mentioned he was waiting for the 3.4 release to build new binaries: https://github.com/HaxeFoundation/hashlink/issues/39#issuecomment-274354866

When it's relatively easy to install hl on Ubuntu, I'll give it a shot for travix.

**Comment by kevinresol** [comment]
done now
