### ISSUE TITLE
PHP broken

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#114]
https://travis-ci.org/haxetink/tink_testrunner/jobs/530150284#L1033

looks like some php packages are no longer available?

**Comment by back2dos** [comment]
"PHP Broken" ... what else is new? :D

**Comment by andyli** [comment]
It's probably because launchpad removed Trusty support since Trusty went EOL.

**Comment by back2dos** [comment]
What's our best upgrade path?

**Comment by kevinresol** [comment]
> What's our best upgrade path?

Update to xenial fixes it, not sure if we still want to support trusty.

**Comment by andyli** [comment]
Dropping Trusty is the "right" thing to do, it's just I guess people will be confused when their build breaks suddenly. What about adding an OS check in travix that detects Trusty and throw an error message about it?

**Comment by sebthom** [comment]
I seem to recall that Haxe 3.4 + Lua only works on Trusty.

**Comment by FrancisBourre** [comment]
My builds are broken, any news about what should/could I do please? :)
https://travis-ci.org/DoclerLabs/hexCore/jobs/568342779
https://travis-ci.org/DoclerLabs/hexCore/jobs/568342780

**Comment by kevinresol** [comment]
You should use xenial instead of trusty

**Comment by FrancisBourre** [comment]
Thanks, work fine now.

**Comment by sebthom** [comment]
I am closing this issue for now. Trusty is "End of Standard Support" by Canonical and Xenial the default in Travis now anyways. Feel free to reopen if required.
