### ISSUE TITLE
new haxelib release? 

### ISSUE THREAD

**Issue by sebthom** [back2dos/travix#115]
hey guys,
would you mind pushing a new release to haxelib? the last one is 8months old and for example the flash amd HL targets don't work anymore.

Thanks, 
Seb

**Comment by kevinresol** [comment]
Just tried but php is broken (#114), blocking the [CI](https://travis-ci.org/back2dos/travix/jobs/530621577)...

**Comment by back2dos** [comment]
You can release via tagging at any time - assuming the CI passes.

**Comment by sebthom** [comment]
Thanks for the new release!
