### ISSUE TITLE
Builds on travis-ci.org ceased

### ISSUE THREAD

**Issue by sebthom** [back2dos/travix#129]
Can the builds be migrated to travis-ci.com?

![image](https://user-images.githubusercontent.com/426959/128251935-8a04488b-16d9-4306-8d92-46ad096cee06.png)

**Comment by cedx** [comment]
Is this issue still valid? It seems that Tinkerbell libs are now using GitHub Actions.

**Comment by sebthom** [comment]
Since this is a build helper for travis it would make sense to have travis builds. Because of some limitations and recent issues with travix, I now replaced it with [haxe-reusable-workflows](https://github.com/vegardit/haxe-reusable-workflows/), so I don't mind to close the issue.
