### ISSUE TITLE
Build arguments per target?

### ISSUE THREAD

**Issue by ciscoheat** [back2dos/travix#14]
Is there a best way of defining build arguments for a specific target in travix? I'd like to add `-D nodejs` for only the node build.

PS. Great project! So convenient. :)

**Comment by kevinresol** [comment]
I think it works already, like `haxelib run travix node -D nodejs`

**Comment by back2dos** [comment]
Indeed. Please note though that `travix node` implicitly runs with `-lib hxnodejs` which also sets `-D nodejs`, so there's no need to do that. Does that answer your question?

**Comment by ciscoheat** [comment]
So that's why it worked anyway! Yes it does, thank you.
