### ISSUE TITLE
Travix fails with Haxe 4.3 nightly

### ISSUE THREAD

**Issue by sebthom** [back2dos/travix#143]
The following compiler error is reported:
```haxe
/opt/hostedtoolcache/haxe/lib/travix/git/src/travix/commands/AuthCommand.hx:121: characters 4-16 : tink.core.Noise should be tink.core.Error
/opt/hostedtoolcache/haxe/lib/travix/git/src/travix/commands/AuthCommand.hx:121: characters 4-16 : ... For function argument 'f'
/opt/hostedtoolcache/haxe/lib/travix/git/src/travix/commands/AuthCommand.hx:121: characters 4-16 : tink.core.Noise should be tink.core.Error
/opt/hostedtoolcache/haxe/lib/travix/git/src/travix/commands/AuthCommand.hx:121: characters 4-16 : ... For function argument 'f'
Error: Process completed with exit code 1.
```

@back2dos @kevinresol can one of you please have a look. I am not familiar with tink. thanks!

**Comment by kevinresol** [comment]
Looks like the implicit cast has broken again...

**Comment by sebthom** [comment]
@kevinresol I am now also seeing this with tink_testrunner. would you be able to open a ticket against the Haxe repo with a stripped down reproducible test case so they can address it?

**Comment by back2dos** [comment]
This required https://github.com/HaxeFoundation/haxe/issues/10739 to fix (so must have https://github.com/HaxeFoundation/haxe/commit/2f60b84be6c7c20eec5735575957e517c83ac01a or later), and tink_core@2.1.0
