### ISSUE TITLE
Exit status from flash

### ISSUE THREAD

**Issue by ciscoheat** [back2dos/travix#15]
In the buddy tests, I'm configuring flash to exit with a CI status: https://github.com/ciscoheat/buddy/blob/master/flash-travis-setup.sh#L14-L19

It's a bit messy, but enables a `Sys.exit` call in flash: `flash.system.System.exit`

Unfortunately the flash debugger is quite unstable, so running the tests is awkward: https://github.com/ciscoheat/buddy/blob/master/flash-travis-run.sh

I'm not sure I can do a useful PR for this one, but it's a start if you're interested.

**Comment by kevinresol** [comment]
That run script looks *really* hacky :joy:
But why not? things that work hackily is better than not working :+1:

**Comment by ciscoheat** [comment]
Yeah, I wish I'd found any other way to do it... :) Maybe you can crack it? (I've only tested it on Ubuntu 12.04).

**Comment by kevinresol** [comment]
Crack what? I have no idea about the flash debugger...

**Comment by ciscoheat** [comment]
Crack a way of running it without the current "statistical" approach.

**Comment by back2dos** [comment]
Seems to be dealt with by #18
