### ISSUE TITLE
Add command: checkstyle

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#16]
a nice-to-have:
`haxelib run travix checkstyle`

https://github.com/HaxeCheckstyle/haxe-checkstyle

**Comment by back2dos** [comment]
Sure, why not :)

**Comment by kevinresol** [comment]
I didn't have a chance to try the library yet. I will find some time to try it and see if we can integrate it with travix.

**Comment by kevinresol** [comment]
Let's forget about this
