### ISSUE TITLE
Bootstrap the RunTest class

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#17]
Simply create the minimal class file under the tests folder, during `travix init`

**Comment by back2dos** [comment]
I'm not really sure about this one. What would such a class look like, really?

**Comment by kevinresol** [comment]
It would be something like the following, only created if it does not exists yet.
The purpose is just to save a minute of creating the folder and file.
Maybe I am just too lazy to do that manually....

```haxe
class RunTests {
  static function main() {
    trace("it works!");
  }
}

**Comment by back2dos** [comment]
Sure, why not ;)
