### ISSUE TITLE
Flash fails

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#20]
https://travis-ci.org/haxetink/tink_core/jobs/135422030
I have no idea what is going on.
@ciscoheat can you have a look please?

**Comment by ciscoheat** [comment]
You need to follow the travix instructions about building on flash. :) The
docs are updated, now when it's not only compiling, it needs to exit
explicitly.

Den sön 5 jun 2016 18:48Kevin Leung <notifications@github.com> skrev:

**Comment by back2dos** [comment]
Haha, yep, that freaked me out too. But I fixed it now (for tink_core and tink_io at least). So everything is alright ;)
