### ISSUE TITLE
ask() should wait for the enter key

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#32]
https://github.com/back2dos/travix/blob/94f131d/src/travix/Command.hx#L43

Currently `ask()` reacts as soon as a key is pressed which is not a usual practice for command line tools. I suggest replacing `Sys.getChar()` with `Sys.stdin().readLine()`

**Comment by back2dos** [comment]
Sorry, I though I had responded to this a while back, but obviously not.

I guess this is a good idea, but rather because `Sys.getChar()` is sometimes broken if haxelib is being invoked through too many layers (e.g. `npm run ...`).

So yeah, feel free to go ahead on this ;)

**Comment by sebthom** [comment]
Fixed with https://github.com/back2dos/travix/commit/6e100735845e833a14b41c0891402b16583cfec7#diff-08ea7a4e51dfd89964f6b8ccca0c6088
