### ISSUE TITLE
Flash times out all the time.

### ISSUE THREAD

**Issue by back2dos** [back2dos/travix#33]
Can someone else confirm this? cc @ciscoheat @kevinresol

**Comment by ciscoheat** [comment]
It's working fine for me: https://travis-ci.org/ciscoheat/HaxeContracts/jobs/166066684#L369-L977

But I've been having some problems with php lately, it seems that xdebug is limiting the stack depth just enough so that buddy will have problem sometimes. The way to fix that is to add the following in `.travis.yml`:

```
before_script:
  - phpenv config-rm xdebug.ini || true 
```

**Comment by back2dos** [comment]
Weird. Ok, I'll observe this further.

As for the xdebug oddity, I guess it'd be best to just make that a part of the travix php command.

**Comment by aliokan** [comment]
I met this issue on hexMachina tests : https://travis-ci.org/DoclerLabs/hexMachina/jobs/168381089#L1133-L1736

**Comment by ciscoheat** [comment]
The flash test process is quite unstable, and I don't know how it works with `-swf-version` and `-swf-header`. Could that be a part of the problem?

**Comment by sebthom** [comment]
Is that still an issue? I got some timeouts in one project and could solve it by using `-D swf-script-timeout=180` in my build.hxml

**Comment by kevinresol** [comment]
Is it working now? I am having `Flash execution failed too many times, build failure.`

https://travis-ci.org/haxetink/tink_validation/jobs/310115777#L553

**Comment by kevinresol** [comment]
Flash works about 25% of the time.

**Comment by back2dos** [comment]
![70836500](https://user-images.githubusercontent.com/509501/57093199-81ba8d80-6d0d-11e9-969e-255f9bbce496.jpg)
