### ISSUE TITLE
Java no longer installed by default

### ISSUE THREAD

**Issue by back2dos** [back2dos/travix#36]
I've recently encountered this error repeatedly: https://travis-ci.org/haxetink/tink_core/jobs/180778761#L1091

**Comment by andyli** [comment]
It's travis's bug: https://github.com/travis-ci/travis-ci/issues/6928
We can use `jdk_switcher use oraclejdk7` to workaround for now.

**Comment by kevinresol** [comment]
I think it is done now: https://docs.travis-ci.com/user/build-environment-updates/2016-12-06/
