### ISSUE TITLE
Shall we update the default haxe version?

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#38]
I use this now: https://github.com/kevinresol/tink_unittest/blob/5900b12/.travis.yml#L10-L13

**Comment by back2dos** [comment]
Technically 3.2.1 is still the last stable. Under the assumption that 3.4 is released any time soon I think it'd be best to just wait for that and make it the new default. But if you feel strongly about it, I don't mind making an update now and then again later for 3.4.

**Comment by kevinresol** [comment]
Nothing can be more uncertain than the release date of Haxe, other than the return of Jesus Christ.
But let just wait for a while :smile:

**Comment by fponticelli** [comment]
It is time now :)

**Comment by back2dos** [comment]
Who wants to do the honors?

**Comment by ciscoheat** [comment]
Should we simply replace 3.2.1 in `default.yml`, or devise a way to exclude newer targets from older releases?

**Comment by back2dos** [comment]
In principle it would be good to have a way to just skip targets that the chosen Haxe version does not support. OTOH I'm not sure that's really a thing right now. Let's do the simplest thing for now and see if anyone complains.

**Comment by back2dos** [comment]
Done.
