### ISSUE TITLE
Latest hxcpp can't build on Mac

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#4]
First of all, I [removed the apt-get (brew) call of installing gcc on Mac](https://github.com/kevinresol/travix/commit/420bc867cd97e2378f97b16bf9bc60b19cdc8947). But then I ran into issue about building hxcpp: https://travis-ci.org/kevinresol/hashids/jobs/120223739#L1045

I am not sure if it is related to the gcc compiler or what? Because the thing builds fine on Linux.

**Comment by back2dos** [comment]
Is this still an issue? The built you've linked seems to have passed?

**Comment by kevinresol** [comment]
Seems fixed by itself...
