### ISSUE TITLE
Usage with lix

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#51]
Currently, in a lixified project, travix tries to install missing libs (e.g. hxnodejs) with `haxelib` instead of `lix`, causing the build to fail, where lix is used to resolve libs.

**Comment by kevinresol** [comment]
And I have no idea what this is: https://travis-ci.org/haxetink/tink_streams/builds/223474471#L370-L387

**Comment by back2dos** [comment]
The error is probably because `haxelib run hxcpp` winds up in a different path and is unable to locate the local config, winds up looking for the global one which doesn't exist and thus fails.

**Comment by kevinresol** [comment]
> The error is probably because haxelib run hxcpp winds up in a different path

iirc, that command runs in where the Build.xml is, in this case `bin/cpp`

**Comment by kevinresol** [comment]
I managed to make cpp work by running `npm install -g switchx && switchx` first.

**Comment by kevinresol** [comment]
Seems working fine with latest travix
