### ISSUE TITLE
Allow specifying hxml

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#52]
Instead of hardcoded as `tests.hxml`

**Comment by back2dos** [comment]
If we just omit `tests.hxml` if it is missing then that would do the trick, because one can append arbitrary arguments anyway.

**Comment by kevinresol** [comment]
What is the decision here?

Another related stuff is that I would like support non-libraries, by removing [`-lib lib_name_from_haxelib_json`](https://github.com/back2dos/travix/blob/6e100735845e833a14b41c0891402b16583cfec7/src/travix/Command.hx#L143)
and move that into tests.hxml itself

**Comment by back2dos** [comment]
I think you should just check if there's a tests.hxml and otherwise not pass it to the compiler.
Similarly for non-lib tests, I would check if the haxelib.json exists and otherwise not generate that -lib argument.

**Comment by kevinresol** [comment]
Updated: https://github.com/back2dos/travix/commit/06c63560a15ccc90bc664cc5b15dbabddc000673

But there is a (minor) problem, that you cannot reliably pass relative class path with the `-cp` argument. See https://github.com/HaxeFoundation/haxelib/issues/387
