### ISSUE TITLE
[error] Library travix version dev does not have a run script

### ISSUE THREAD

**Issue by sebthom** [back2dos/travix#56]
Documentation says:
```
How to use git version

In your .travis.yml simply replace haxelib install travix with the following:

haxelib git travix https://github.com/back2dos/travix
```

However that fails with `Library travix version dev does not have a run script`

**Comment by kevinresol** [comment]
The readme needs to be updated.
For now you can just cd to the directory and run `haxe build-neko.hxml`

**Comment by back2dos** [comment]
Remind me: why did we actually ditch the interpreter?

**Comment by kevinresol** [comment]
iirc, it is for a more reliable detection for the cwd arg at the end of the list:
https://github.com/back2dos/travix/commit/80389050cba244cf5c56242d29409d6708d473fd#diff-c62cfad9137c0d34500749e5d0f30badR83

**Comment by back2dos** [comment]
Yeah, I see.
