### ISSUE TITLE
[error] C++, C#, Java targets fail with 'command not found'

### ISSUE THREAD

**Issue by sebthom** [back2dos/travix#57]
Travix assumes the file name of the compiled binary is based on the fully qualified class name. However, it is only based on the simple classname (without package).

C++ targets fail with
```
travis_fold:end:build-cpp.1
> ./bin/com/example/TestRunner
sh: 1: ./bin/com.example.TestRunner: not found
```

C# targets fail with
```
haxelib run hxcs hxcs_build.txt --haxe-version 3201 --feature-level 1
travis_fold:end:build-cs.1
> mono bin/cs/bin/com/example/TestRunner.exe
Cannot open assembly 'bin/cs/bin/com.example.TestRunner.exe': No such file or directory.
```

Java targets fail with
```
travis_fold:end:build-java.1
> java -jar bin/java/com.example.TestRunner.jar
Error: Unable to access jarfile bin/java/com.example.TestRunner.jar
```

**Comment by kevinresol** [comment]
https://github.com/back2dos/travix/blob/80389050cba244cf5c56242d29409d6708d473fd/src/travix/Travix.hx#L44

Can you try changing this line to ` return Some(line.substr(5).split('.').pop().trim());`?
