### ISSUE TITLE
Using travix.Logger only for travis builds

### ISSUE THREAD

**Issue by sebthom** [back2dos/travix#58]
Documentation recommends to use travix.Logger over trace() and Sys.exit()

Does travix set a compiler flag when invoking the Haxe compiler so I could use a conditional in my classes? For example:

```haxe
#if travix
    travix.Logger.trace(...);
#else
    trace(...):
#end
```

**Comment by kevinresol** [comment]
When you use a library, the library name is set as a define.
So yes, you can do that.
