### ISSUE TITLE
debug flag in hxml

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#6]
Some targets (e.g. c++) output a different executable name when debug flag is set, e.g. "RunTests" vs "RunTests-debug", causing travix fail to execute the output.

**Comment by back2dos** [comment]
I'm inclined to use Context.onAfterGenerate to just rename the file to what travix expects. Thoughts?

**Comment by kevinresol** [comment]
I am not sure if that will cause problems if I switch between debug and release often. I think a better way is to parse the hxml file and execute the corresponding file after checking the existent of `-debug`.

Another benefit is that `travix install` can install any dependencies for the test (but not the library). For example my tests use `-lib buddy` and I need to add `haxelib install buddy` in travis.yml manually currently.
