### ISSUE TITLE
Build travix with --no-traces

### ISSUE THREAD

**Issue by back2dos** [back2dos/travix#69]
Occasionally we have traces left in travix (this time for once it wasn't me \o/). I propose putting `--no-traces` into the `build-neko.hxml` and `build-node.hxml`, but maybe that's a bit overkill?

**Comment by kevinresol** [comment]
I just removed the trace, after 6 months: https://github.com/back2dos/travix/commit/06c63560a15ccc90bc664cc5b15dbabddc000673#diff-08ea7a4e51dfd89964f6b8ccca0c6088R149
