### ISSUE TITLE
cpp failure on mac

### ISSUE THREAD

**Issue by fponticelli** [back2dos/travix#7]
I am porting thx.core to travix. The setup is magically simple!
Once I run my tests here: https://travis-ci.org/fponticelli/thx.core/builds/127977150
I get this error here: https://travis-ci.org/fponticelli/thx.core/jobs/127977154#L253
It is mac only and it is not related (?) to my haxe code:

```
1.00s$ haxelib run travix cpp
> brew install gcc-multilib
Error: No available formula for gcc-multilib 
```

Any idea?

**Comment by kevinresol** [comment]
This should be fixed https://github.com/back2dos/travix/commit/c595f1895a78204f9d5b6f1257c5a74f6ea34145
Just need a fresh release. 
@back2dos would you please?

**Comment by back2dos** [comment]
@kevinresol Done. You do have submit rights on haxelib, so don't be afraid to use them ;)

@fponticelli Glad you like it. Please confirm this works for you now.

**Comment by kevinresol** [comment]
I'm really bad at submitting haxelib. 
Is `haxelib submit`ing a zip the only way? I found that `npm publish ` is more pleasant to use in a sense that I dont need to pick and zip the files manually

**Comment by fponticelli** [comment]
Works beautifully, thanks!
