### ISSUE TITLE
Using "haxelib run travix php" with Haxe 4 fails

### ISSUE THREAD

**Issue by sebthom** [back2dos/travix#70]
Haxe 4 dropped support for PHP5, thus the default output format is PHP7.

```bash
> haxe -php bin/php -lib travix -lib haxe-concurrent tests.hxml
> php5.6 -d xdebug.max_nesting_level=9999 bin/php/index.php
PHP Parse error:  syntax error, unexpected '?' in /home/travis/build/vegardit/haxe-concurrent/bin/php/lib/php/Boot.php on line 53
```

So travix should select Php7Command.hx instead of PhpCommand.hx when Haxe 4 is detected or PhpCommand.hx should install php7 instead of php56 when Haxe 4 is detected.

Any thoughts?

**Comment by back2dos** [comment]
Gnieh. Not really, to be honest. Looks like for better or worse the decision to drop PHP5 is final. In that case, I'd say this is the best course of action:

> travix should select Php7Command.hx instead of PhpCommand.hx when Haxe 4 is detected
