### ISSUE TITLE
[flash] "Application crashed with an unhandled SIGSEGV"

### ISSUE THREAD

**Issue by azrafe7** [back2dos/travix#76]
First off, thank you for this lib, very handy (and super-easy to use)!

To the issue:
testing flash seems to always result in an error saying `Xlib:  extension "RANDR" missing on display ":99"` (but still reporting that `The command "haxelib run travix flash" exited with 0.`, so marking it as a success). 

I'm not sure how/if I can play with the lib and make my own tests to try and fix the thing (advice?), but in the meantime I've found [this post on askubuntu](https://askubuntu.com/questions/754382/how-do-i-start-chromium-browser-in-headless-mode-extension-randr-missing-on-d). 
Not sure it that can be of help, but the other ones I dug up on SO had controversial comments.

**Comment by sebthom** [comment]
The "Xlib: extension "RANDR" missing" is only a warning and should not have an influence on the exit code.

I don't know which travix version you used. I tried to address the warning by recently adding 
`+extension RANDR` to `xvfb-run` . See https://github.com/back2dos/travix/blob/master/src/travix/commands/FlashCommand.hx#L65

**Comment by sebthom** [comment]
can you try running your build with the latest travix code, like so: https://github.com/back2dos/travix/blob/master/src/travix/default.yml#L22

**Comment by azrafe7** [comment]
Yes, tried [exactly that](https://travis-ci.org/azrafe7/wideint/jobs/299196085#L427) a couple of hours ago.

In the output it still complains about RANDR (https://travis-ci.org/azrafe7/wideint/jobs/299196085#L1014), and there's no sign if the swf is being run or not.

**Comment by sebthom** [comment]
hmm, the flash debug player crashes during execution with "Application crashed with an unhandled SIGSEGV". no idea why.

**Comment by sebthom** [comment]
This seems to be an issue with the trusty linux distribution on travis: https://github.com/travis-ci/travis-ci/issues/8481

**Comment by back2dos** [comment]
What to do here? Just forget about flash? :D

**Comment by sebthom** [comment]
Maybe it works with Ubuntu Xenial? https://blog.travis-ci.com/2018-11-08-xenial-release

**Comment by kevinresol** [comment]
It works once like every 4 trials. But we don't really have a solution.
