### ISSUE TITLE
support Phantomjs

### ISSUE THREAD

**Issue by fponticelli** [back2dos/travix#8]
It would be really great if you could support phantomjs in the tests. Libraries like `doom` would certainly take advantage of that ;)

The way I do it is this:

```js
var page = require('webpage').create();
page.onConsoleMessage = function (msg) { console.log(msg); };
var url = './bin/index.html';

page.open(url, function (status) {
  function check() {
    return page.evaluate(function() { return window.utest_result; });
  }
  function poll(callback) {
    var result = check();
    if(result) {
      return callback(result);
    }
    setTimeout(function() { poll(callback); }, 1000);
  }
  poll(function(result) {
    if(result.isOk) {
      console.log('phantom.js: test successful');
      console.log(result.message);
      phantom.exit();
    } else {fu
      console.log('phantom.js: test errors');
      console.log(result.message);
      phantom.exit(1);
    }
  });
});
```

The testing library is expected to set a global variable `utest_result` on `window` to signal the completion of the tests. Obviously the name doesn't have to be that one and in more recent versions of phantom there might be better ways to communicate to the host.

**Comment by kevinresol** [comment]
I will have a closer look on this one

**Comment by kevinresol** [comment]
After some reading I found that phantomjs supports callback from the page script, like so:

```js
// page script:
if (typeof window.callPhantom === 'function') {
  window.callPhantom({ hello: 'world' });
}

// phantom script:
var webPage = require('webpage');
var page = webPage.create();

page.onCallback = function(data) {
  console.log('CALLBACK: ' + JSON.stringify(data));
  // Prints 'CALLBACK: { "hello": "world" }'
};
```

So I would like to propose defining a "travix message standard", that test frameworks can use.
It could be something like this: 
```js
window.callPhantom({
    cmd: 'travix:log',
    message: myMessage
});
window.callPhantom({
    cmd: 'travix:exit',
    exitCode: myExitCode
});
```
Travix will prepare a phantom script which will act correspondingly to these commands.
And in every test frameworks that would like to support travix, they only need to depend on a compiler flag (say `travix`, which is set by travix's build command) to include the above code.

How does that sound? @fponticelli @ciscoheat @back2dos

**Comment by back2dos** [comment]
Hehe. Ok, well @kevinresol , it seems we have [similar opinions](https://github.com/back2dos/travix/issues/25#issuecomment-225490829) :)

**Comment by kevinresol** [comment]
I think we are done here, js is a supported target now
