### ISSUE TITLE
Switch from PhantomJs to Headless Chrome

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#80]
PhantomJS is no longer maintained. https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

**Comment by sebthom** [comment]
And/or [SlimerJS](https://slimerjs.org/)?

**Comment by kevinresol** [comment]
yeah why not?
I think with tink_cli now it is easy to add flags to switch between the two like `--runtime=headless-chrome` or `--runtime=slimerjs`

**Comment by back2dos** [comment]
Wohoo :)
