### ISSUE TITLE
How to use a haxelib only for a specific target

### ISSUE THREAD

**Issue by sebthom** [back2dos/travix#85]
How can I configure travix to only add a haxelib e.g. [phantomjs](http://lib.haxe.org/p/phantomjs/) to the build path when targeting JS. If I simply add it globally to `tests.hxml` then the other sys targets will fail with "You cannot access the js package while targeting cpp (for js.phantomjs.FileSystem)".

**Comment by kevinresol** [comment]
You can do so by adding compiler arguments when you run travix:

`haxelib run travix js -lib phantomjs`
