### ISSUE TITLE
travix all

### ISSUE THREAD

**Issue by fponticelli** [back2dos/travix#9]
It would be very convenient if `travix all` could run all the tests for all the platforms defined in the `.travis` file and stop on the first failure.

**Comment by back2dos** [comment]
Uhm, isn't some ruby gem or to install the travis runner locally that would
do just that?

I don't want travix to have depencies, so parsing yaml properly is going to
be hard, while some quick and dirty parsing comes with it's own issues. Of
course if you feel like adding and maintaining such a feature, I would be
more than happy :)

**Comment by fponticelli** [comment]
I don't know much about Travis in general so you might be right that a command already exists. There is a nice YAML library for haxe but that would definitely be a dependency.

**Comment by kevinresol** [comment]
Closing due to lack of interest in general.
