### ISSUE TITLE
Build fails on osx by trying to do linuxy things

### ISSUE THREAD

**Issue by thomasjwebb** [back2dos/travix#91]
I don't know if this is from me doing something wrong, but I added osx to my `.travis.yml` and it [fails just on flash and js](https://travis-ci.org/osakared/grig.pitch/jobs/381805681) and for both it looks like may be doing something that I wouldn't expect on macos:

```
$ haxelib run travix js
installPackage-phantomjs.3
> brew update
Already up-to-date.
> brew install phantomjs
==> Downloading https://homebrew.bintray.com/bottles/phantomjs-2.1.1.sierra.bottle.1.tar.gz
==> Pouring phantomjs-2.1.1.sierra.bottle.1.tar.gz
🍺  /usr/local/Cellar/phantomjs/2.1.1: 49 files, 50.5MB
build-js.3
> haxe -js bin/js/tests.js -lib travix -lib grig.pitch tests.hxml
> phantomjs-2.1.1-linux-x86_64/bin/phantomjs -v
sh: phantomjs-2.1.1-linux-x86_64/bin/phantomjs: No such file or directory
The command "haxelib run travix js" exited with 127.
```

`phantomjs-2.1.1-linux-x86_64` contains "linux" (is travix moving away from using phantomjs anyway?)

```
1.35s$ haxelib run travix flash
FlashCommand.hx:15: Don't know how to install Flash on Mac
build-flash.4
> haxe -swf bin/swf/tests.swf -D flash-exit -lib travix -lib grig.pitch tests.hxml
sh: xvfb-run: command not found
sh: xvfb-run: command not found
sh: xvfb-run: command not found
sh: xvfb-run: command not found
sh: xvfb-run: command not found
sh: xvfb-run: command not found
sh: xvfb-run: command not found
> eval ps aux | grep -ie [L]ogs/flashlog.txt | awk '{print $2}' | xargs kill -9
grep: /Users/travis/.macromedia/Flash_Player/Logs/flashlog.txt: No such file or directory
Flash execution failed too many times, build failure.
The command "haxelib run travix flash" exited with 1.
```

xvfb-run is used with x11-based applications. but I'm guessing that failing to run is the cause of the subsequent errors...

**Comment by thomasjwebb** [comment]
Ah I'm dumb. I didn't notice `FlashCommand.hx:15: Don't know how to install Flash on Mac` I'm guessing testing flash isn't implemented outside linux yet?

**Comment by back2dos** [comment]
> I didn't notice `FlashCommand.hx:15: Don't know how to install Flash on Mac` I'm guessing testing flash isn't implemented outside linux yet?

IIRC it did work correctly at some point and I'm guessing the reason it doesn't is that [Apple dropped X11 support a year ago](https://support.apple.com/en-us/HT201341).

I must admit I'm not using Mac on Travis anyway, because it takes a lot longer for jobs to start and things break randomly because Apple. The most pragmatic thing to do IMHO is to skip all but the hxcpp, hl/c and neko tests on Mac, because that's those are the only ones that truly differ.

**Comment by andyli** [comment]
Flash testing on Mac still works on my side: https://github.com/andyli/HaxeCI
You may take the code you need there.

**Comment by kevinresol** [comment]
Original issue addressed.

**Comment by back2dos** [comment]
It was? ^^

Seems we still have an issue with phantom, but ok, there's a ticket for that anyway.

**Comment by thomasjwebb** [comment]
The issue with it not installing Mac shouldn't be difficult to fix, however it also doesn't seem important because in theory the behavior should be the same as Linux. And I ended up disabling flash for now because it randomly crashes on me.
