### ISSUE TITLE
C# doesn't like Buddy?

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#92]
https://travis-ci.org/back2dos/travix/jobs/382188026#L2821

**Comment by back2dos** [comment]
Seems so. As far as I can tell that's pretty recent though, which leaves me a bit puzzled ^^

**Comment by ciscoheat** [comment]
I'll take a look and try to figure out if the problem is in Buddy or somewhere else.

**Comment by back2dos** [comment]
Any news here?

**Comment by kevinresol** [comment]
Using tink_unittest now
